# https://github.com/devcontainers/templates/blob/main/src/dotnet/.devcontainer/devcontainer.json
# TODO: clone this properly
# [Choice] Java version (use -bullseye variants on local arm64/Apple Silicon): 11, 17, 11-bullseye, 17-bullseye, 11-buster, 17-buster
ARG VARIANT=20
FROM mcr.microsoft.com/devcontainers/typescript-node:${VARIANT}