/* tslint:disable */
/* eslint-disable */
/**
 * BetMonitor for generating matches and Odds
 * The server for simulating a betting portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BetDto,
} from '../models/index';
import {
    BetDtoFromJSON,
    BetDtoToJSON,
} from '../models/index';

/**
 * 
 */
export class BetsApi extends runtime.BaseAPI {

    /**
     * Get user pending bets.
     */
    async getUserBetsPendingRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BetDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/user/bets/pending`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BetDtoFromJSON));
    }

    /**
     * Get user pending bets.
     */
    async getUserBetsPending(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BetDto>> {
        const response = await this.getUserBetsPendingRaw(initOverrides);
        return await response.value();
    }

}
