/* tslint:disable */
/* eslint-disable */
/**
 * BetMonitor for generating matches and Odds
 * The server for simulating a betting portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  LeagueDto,
} from '../models/index.js';
import {
    LeagueDtoFromJSON,
    LeagueDtoToJSON,
} from '../models/index.js';

/**
 * 
 */
export class LeaguesApi extends runtime.BaseAPI {

    /**
     * Get all leagues.
     */
    async getAllLeaguesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LeagueDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/leagues`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LeagueDtoFromJSON));
    }

    /**
     * Get all leagues.
     */
    async getAllLeagues(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LeagueDto>> {
        const response = await this.getAllLeaguesRaw(initOverrides);
        return await response.value();
    }

}
