/* tslint:disable */
/* eslint-disable */
/**
 * BetMonitor for generating matches and Odds
 * The server for simulating a betting portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MatchDto,
} from '../models/index';
import {
    MatchDtoFromJSON,
    MatchDtoToJSON,
} from '../models/index';

export interface GetMatchesRequest {
    from?: Date;
    to?: Date;
}

/**
 * 
 */
export class MatchesApi extends runtime.BaseAPI {

    /**
     * Get all matches or matches between dates.
     */
    async getMatchesRaw(requestParameters: GetMatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MatchDto>>> {
        const queryParameters: any = {};

        if (requestParameters.from !== undefined) {
            queryParameters['from'] = (requestParameters.from as any).toISOString();
        }

        if (requestParameters.to !== undefined) {
            queryParameters['to'] = (requestParameters.to as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/matches`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MatchDtoFromJSON));
    }

    /**
     * Get all matches or matches between dates.
     */
    async getMatches(requestParameters: GetMatchesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MatchDto>> {
        const response = await this.getMatchesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get recent matches.
     */
    async getRecentMatchesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MatchDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/matches/recent`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MatchDtoFromJSON));
    }

    /**
     * Get recent matches.
     */
    async getRecentMatches(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MatchDto>> {
        const response = await this.getRecentMatchesRaw(initOverrides);
        return await response.value();
    }

}
