/* tslint:disable */
/* eslint-disable */
/**
 * BetMonitor for generating matches and Odds
 * The server for simulating a betting portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Hold id primary key auto generated column.
 * @export
 * @interface BaseSchemaId
 */
export interface BaseSchemaId {
    /**
     * 
     * @type {number}
     * @memberof BaseSchemaId
     */
    id: number;
}

/**
 * Check if a given object implements the BaseSchemaId interface.
 */
export function instanceOfBaseSchemaId(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function BaseSchemaIdFromJSON(json: any): BaseSchemaId {
    return BaseSchemaIdFromJSONTyped(json, false);
}

export function BaseSchemaIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseSchemaId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function BaseSchemaIdToJSON(value?: BaseSchemaId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

