/* tslint:disable */
/* eslint-disable */
/**
 * BetMonitor for generating matches and Odds
 * The server for simulating a betting portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Holds created_at and updated_at auto generated columns.
 * @export
 * @interface BaseSchemaDates
 */
export interface BaseSchemaDates {
    /**
     * 
     * @type {Date}
     * @memberof BaseSchemaDates
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BaseSchemaDates
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the BaseSchemaDates interface.
 */
export function instanceOfBaseSchemaDates(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BaseSchemaDatesFromJSON(json: any): BaseSchemaDates {
    return BaseSchemaDatesFromJSONTyped(json, false);
}

export function BaseSchemaDatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseSchemaDates {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function BaseSchemaDatesToJSON(value?: BaseSchemaDates | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

