/* tslint:disable */
/* eslint-disable */
/**
 * BetMonitor for generating matches and Odds
 * The server for simulating a betting portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A request body of a wager placed by a user on a marketState.
 * @export
 * @interface BetPlaceDto
 */
export interface BetPlaceDto {
    /**
     * 
     * @type {number}
     * @memberof BetPlaceDto
     */
    stake: number;
    /**
     * 
     * @type {number}
     * @memberof BetPlaceDto
     */
    marketStateId: number;
}

/**
 * Check if a given object implements the BetPlaceDto interface.
 */
export function instanceOfBetPlaceDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "stake" in value;
    isInstance = isInstance && "marketStateId" in value;

    return isInstance;
}

export function BetPlaceDtoFromJSON(json: any): BetPlaceDto {
    return BetPlaceDtoFromJSONTyped(json, false);
}

export function BetPlaceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetPlaceDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stake': json['stake'],
        'marketStateId': json['marketStateId'],
    };
}

export function BetPlaceDtoToJSON(value?: BetPlaceDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stake': value.stake,
        'marketStateId': value.marketStateId,
    };
}

