/* tslint:disable */
/* eslint-disable */
/**
 * BetMonitor for generating matches and Odds
 * The server for simulating a betting portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MarketDto } from './MarketDto';
import {
    MarketDtoFromJSON,
    MarketDtoFromJSONTyped,
    MarketDtoToJSON,
} from './MarketDto';
import type { PlayerDto1 } from './PlayerDto1';
import {
    PlayerDto1FromJSON,
    PlayerDto1FromJSONTyped,
    PlayerDto1ToJSON,
} from './PlayerDto1';

/**
 * 
 * @export
 * @interface MarketStateDto
 */
export interface MarketStateDto {
    /**
     * 
     * @type {number}
     * @memberof MarketStateDto
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof MarketStateDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MarketStateDto
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof MarketStateDto
     */
    odd: number;
    /**
     * 
     * @type {boolean}
     * @memberof MarketStateDto
     */
    suspended: boolean;
    /**
     * 
     * @type {number}
     * @memberof MarketStateDto
     */
    stakeLimit?: number;
    /**
     * 
     * @type {MarketDto}
     * @memberof MarketStateDto
     */
    market?: MarketDto;
    /**
     * 
     * @type {PlayerDto1}
     * @memberof MarketStateDto
     */
    player?: PlayerDto1;
}

/**
 * Check if a given object implements the MarketStateDto interface.
 */
export function instanceOfMarketStateDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "odd" in value;
    isInstance = isInstance && "suspended" in value;

    return isInstance;
}

export function MarketStateDtoFromJSON(json: any): MarketStateDto {
    return MarketStateDtoFromJSONTyped(json, false);
}

export function MarketStateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketStateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'odd': json['odd'],
        'suspended': json['suspended'],
        'stakeLimit': !exists(json, 'stakeLimit') ? undefined : json['stakeLimit'],
        'market': !exists(json, 'market') ? undefined : MarketDtoFromJSON(json['market']),
        'player': !exists(json, 'player') ? undefined : PlayerDto1FromJSON(json['player']),
    };
}

export function MarketStateDtoToJSON(value?: MarketStateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'odd': value.odd,
        'suspended': value.suspended,
        'stakeLimit': value.stakeLimit,
        'market': MarketDtoToJSON(value.market),
        'player': PlayerDto1ToJSON(value.player),
    };
}

