/* tslint:disable */
/* eslint-disable */
/**
 * BetMonitor for generating matches and Odds
 * The server for simulating a betting portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { MarketStateDto1 } from './MarketStateDto1.js';
import {
    MarketStateDto1FromJSON,
    MarketStateDto1FromJSONTyped,
    MarketStateDto1ToJSON,
} from './MarketStateDto1.js';

/**
 * 
 * @export
 * @interface MatchStateDto
 */
export interface MatchStateDto {
    /**
     * 
     * @type {number}
     * @memberof MatchStateDto
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof MatchStateDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MatchStateDto
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof MatchStateDto
     */
    pointScore?: string;
    /**
     * 
     * @type {number}
     * @memberof MatchStateDto
     */
    servingIndex?: number;
    /**
     * 
     * @type {string}
     * @memberof MatchStateDto
     */
    setScore?: string;
    /**
     * 
     * @type {Array<MarketStateDto1>}
     * @memberof MatchStateDto
     */
    marketStates?: Array<MarketStateDto1>;
}

/**
 * Check if a given object implements the MatchStateDto interface.
 */
export function instanceOfMatchStateDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function MatchStateDtoFromJSON(json: any): MatchStateDto {
    return MatchStateDtoFromJSONTyped(json, false);
}

export function MatchStateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchStateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'pointScore': !exists(json, 'pointScore') ? undefined : json['pointScore'],
        'servingIndex': !exists(json, 'servingIndex') ? undefined : json['servingIndex'],
        'setScore': !exists(json, 'setScore') ? undefined : json['setScore'],
        'marketStates': !exists(json, 'marketStates') ? undefined : ((json['marketStates'] as Array<any>).map(MarketStateDto1FromJSON)),
    };
}

export function MatchStateDtoToJSON(value?: MatchStateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'pointScore': value.pointScore,
        'servingIndex': value.servingIndex,
        'setScore': value.setScore,
        'marketStates': value.marketStates === undefined ? undefined : ((value.marketStates as Array<any>).map(MarketStateDto1ToJSON)),
    };
}

